//! Catalog management REST endpoints, all scoped under `api_context`.
//!
//! Covers layers, workspaces, namespaces, data sources, stores, styles, layer
//! groups, SQL views and the legacy `/health` + `/server/status` endpoints.
//!
//! Contributes to the shared `api_context` scope (see `routes::mod`).

use actix_web::{web, Scope};

pub fn add_routes(scope: Scope) -> Scope {
    scope
        .route("/health", web::get().to(crate::handlers::health_check))
        .service(
            web::resource("/layers")
                .route(web::get().to(crate::handlers::list_layers))
                .route(web::post().to(crate::handlers::create_layer)),
        )
        .service(
            web::resource("/layers/{layer}")
                .route(web::get().to(crate::handlers::get_layer))
                .route(web::put().to(crate::handlers::update_layer))
                .route(web::delete().to(crate::handlers::delete_layer)),
        )
        .service(
            web::resource("/layers/{layer}/preview")
                .route(web::get().to(crate::handlers::preview_layer)),
        )
        .service(
            web::resource("/layers/{layer}/feature-type")
                .route(web::get().to(crate::handlers::get_layer_feature_type)),
        )
        .service(
            web::resource("/layers/{layer}/features")
                .route(web::get().to(crate::handlers::get_layer_features)),
        )
        .service(
            web::resource("/layers/{layer}/features/{feature}")
                .route(web::get().to(crate::handlers::get_feature)),
        )
        .service(
            web::resource("/workspaces")
                .route(web::get().to(crate::handlers::list_workspaces))
                .route(web::post().to(crate::handlers::create_workspace)),
        )
        .service(
            web::resource("/workspaces/{workspace}")
                .route(web::get().to(crate::handlers::get_workspace))
                .route(web::put().to(crate::handlers::update_workspace))
                .route(web::delete().to(crate::handlers::delete_workspace)),
        )
        // 工作空间维度端点 (GeoServer 标准路径)
        .route(
            "/workspaces/{workspace}/layers",
            web::get().to(crate::handlers::list_workspace_layers),
        )
        .route(
            "/workspaces/{workspace}/datastores",
            web::get().to(crate::handlers::list_workspace_datastores),
        )
        .route(
            "/workspaces/{workspace}/coveragestores",
            web::get().to(crate::handlers::list_workspace_coveragestores),
        )
        .service(
            web::resource("/namespaces")
                .route(web::get().to(crate::handlers::list_namespaces))
                .route(web::post().to(crate::handlers::create_namespace)),
        )
        .service(
            web::resource("/namespaces/{prefix}")
                .route(web::get().to(crate::handlers::get_namespace))
                .route(web::put().to(crate::handlers::update_namespace))
                .route(web::delete().to(crate::handlers::delete_namespace)),
        )
        .route(
            "/server/status",
            web::get().to(crate::handlers::get_server_status),
        )
        // OGC 服务设置 (WMS/WFS/WCS/WMTS/WPS/CSW)
        .service(
            web::resource("/services/{service}/settings")
                .route(web::get().to(crate::handlers::get_service_settings))
                .route(web::put().to(crate::handlers::update_service_settings)),
        )
        .service(
            web::resource("/data-sources")
                .route(web::get().to(crate::handlers::list_data_sources))
                .route(web::post().to(crate::handlers::create_data_source)),
        )
        .route(
            "/data-sources/test",
            web::post().to(crate::handlers::test_connection),
        )
        .route(
            "/data-sources/browse",
            web::get().to(crate::handlers::browse_local),
        )
        .route(
            "/data-sources/s3/browse",
            web::post().to(crate::handlers::browse_s3),
        )
        .route(
            "/data-sources/{name}/tables",
            web::get().to(crate::handlers::get_data_source_tables),
        )
        .service(
            web::resource("/data-sources/{name}")
                .route(web::get().to(crate::handlers::get_data_source))
                .route(web::put().to(crate::handlers::update_data_source))
                .route(web::delete().to(crate::handlers::delete_data_source)),
        )
        .route(
            "/data-sources/{name}/test",
            web::post().to(crate::handlers::test_data_source_connection),
        )
        .service(
            web::resource("/stores")
                .route(web::get().to(crate::handlers::list_stores))
                .route(web::post().to(crate::handlers::create_store)),
        )
        .service(
            web::resource("/stores/{name}")
                .route(web::get().to(crate::handlers::get_store))
                .route(web::put().to(crate::handlers::update_store))
                .route(web::delete().to(crate::handlers::delete_store)),
        )
        .service(
            web::resource("/workspaces/{workspace}/stores")
                .route(web::get().to(crate::handlers::list_workspace_stores))
                .route(web::post().to(crate::handlers::create_workspace_store)),
        )
        .service(
            web::resource("/workspaces/{workspace}/stores/{name}")
                .route(web::get().to(crate::handlers::get_workspace_store)),
        )
        .service(
            web::resource("/layers/{layer}/style")
                .route(web::get().to(crate::handlers::get_layer_style))
                .route(web::put().to(crate::handlers::put_layer_style)),
        )
        .service(
            web::resource("/styles")
                .route(web::get().to(crate::handlers::list_styles))
                .route(web::post().to(crate::handlers::create_style)),
        )
        .service(
            web::resource("/styles/{name}")
                .route(web::get().to(crate::handlers::get_style_by_name))
                .route(web::put().to(crate::handlers::update_style_by_name))
                .route(web::delete().to(crate::handlers::delete_style_by_name)),
        )
        .service(
            web::resource("/layer-groups")
                .route(web::get().to(crate::handlers::list_layer_groups))
                .route(web::post().to(crate::handlers::create_layer_group)),
        )
        .service(
            web::resource("/layer-groups/{name}")
                .route(web::get().to(crate::handlers::get_layer_group))
                .route(web::put().to(crate::handlers::update_layer_group))
                .route(web::delete().to(crate::handlers::delete_layer_group)),
        )
        .service(
            web::resource("/sql-views")
                .route(web::get().to(crate::handlers::list_sql_views))
                .route(web::post().to(crate::handlers::create_sql_view)),
        )
        .route(
            "/sql-views/preview",
            web::post().to(crate::handlers::preview_sql_view),
        )
        .service(
            web::resource("/sql-views/{name}")
                .route(web::get().to(crate::handlers::get_sql_view))
                .route(web::put().to(crate::handlers::update_sql_view))
                .route(web::delete().to(crate::handlers::delete_sql_view)),
        )
}
